import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Check,ChevronDown,Copy,ExternalLink,MapPin,Search,Share2,Sparkles,X}from'lucide-react';
import{activeVenues,concerts,upcomingConcerts,venues,venueById}from'./data';
import{cloudConfigured,createCloudProfile,loadCurrentUser,loadPublicProfile,loadRsvps,saveRsvp}from'./supabase';
import'./styles.css';
const DA=['SØN','MAN','TIR','ONS','TOR','FRE','LØR'],MON=['JAN','FEB','MAR','APR','MAJ','JUN','JUL','AUG','SEP','OKT','NOV','DEC'];
const fmt=d=>{let x=new Date(d+'T12:00:00');return `${DA[x.getDay()]} ${String(x.getDate()).padStart(2,'0')}.${MON[x.getMonth()]}`};
// Delelinket er produktets kerne, så det skal se ud som det, UI'et lover: plusen.dk/anna
export const shareUrl=username=>`${location.origin}/${username}`;
const copyLink=async(username,done)=>{const url=shareUrl(username);try{await navigator.clipboard.writeText(url)}catch{prompt('Kopiér dit link:',url)}done?.()};
function Header({page,setPage,user,onLogin}){return <><div className="marquee"><span>SEND LINKET ✶ FÅ SELSKAB ✶ +1 ✶ KØBENHAVN & OMEGN ✶ SEND LINKET ✶ FÅ SELSKAB ✶ +1 ✶ KØBENHAVN & OMEGN ✶ </span><span aria-hidden>SEND LINKET ✶ FÅ SELSKAB ✶ +1 ✶ KØBENHAVN & OMEGN ✶ SEND LINKET ✶ FÅ SELSKAB ✶ +1 ✶ KØBENHAVN & OMEGN ✶ </span></div><header><button className="logo" onClick={()=>setPage('home')}>+1</button><nav><button className={page==='home'?'active':''} onClick={()=>setPage('home')}>Koncerter</button><button className={page==='venues'?'active':''} onClick={()=>setPage('venues')}>Spillesteder</button><button className={page==='profile'?'active':''} onClick={()=>user?setPage('profile'):onLogin()}>Min liste</button></nav><button className="login" onClick={()=>user?setPage('profile'):onLogin()}>{user?<><span className="tinyavatar">{user.name[0]}</span>{user.name}</>:'Log ind'}</button></header></>}
function ShareCard({user,onLogin,rsvps}){const[copied,setCopied]=useState(false);let going=Object.values(rsvps).filter(x=>x==='going').length,maybe=Object.values(rsvps).filter(x=>x==='maybe').length;return <div className="share-wrap"><i className="tape"/><div className="share-card"><div className="identity"><div className="avatar">{user?.name?.[0]||'J'}</div><div><b>{user?`${user.name}s liste`:'Din koncertliste'}</b><small>plusen.dk/{user?.username||'dit-navn'}</small></div></div><p>Skal til <strong>{going} koncerter</strong> · overvejer <strong>{maybe}</strong><br/>Ét link. Hele din koncertkalender.</p><button onClick={user?()=>copyLink(user.username,()=>{setCopied(true);setTimeout(()=>setCopied(false),2000)}):onLogin}>{user?(copied?'Kopieret!':'Kopiér dit link'):'Lav din liste'} <Copy size={15}/></button></div><div className="star"><i/><i/><span>DEL<br/>MIG!</span></div></div>}
function RsvpButtons({id,value,onChange}){return <div className="actions"><button className={'going '+(value==='going'?'selected':'')} onClick={()=>onChange(id,value==='going'?null:'going')}>{value==='going'?<><Check/> Du kommer!</>:<>+1 Jeg kommer!</>}</button><button className={'maybe '+(value==='maybe'?'selected':'')} onClick={()=>onChange(id,value==='maybe'?null:'maybe')}>{value==='maybe'?<>Måske <Check/></>:<>Måske…</>}</button></div>}
function ConcertList({items,rsvps,onRsvp,empty='Ingen koncerter her endnu.',readOnly=false}){if(!items.length)return <div className="empty">{empty}<Sparkles/></div>;return <div className="concerts">{items.map(c=>{let v=venueById(c.venueId);return <article className="concert" key={c.id}><time>{fmt(c.date)}</time><div className="concert-main"><a className="artist" href={c.url} target="_blank" rel="noopener noreferrer">{c.artist}</a><div className="meta"><button onClick={()=>location.hash=`venue:${v.id}`}>{v.name}</button> · {c.genre}{c.price?` · ${c.price} kr`:''}</div></div>{!readOnly&&<RsvpButtons id={c.id} value={rsvps[c.id]} onChange={onRsvp}/>}</article>})}</div>}
function LoginModal({close,login,pending,error,busy}){const[name,setName]=useState('');useEffect(()=>{const f=e=>e.key==='Escape'&&close();addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[close]);return <div className="modal-bg" role="dialog" aria-modal="true" aria-label="Log ind" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={e=>{e.preventDefault();if(name.trim())login(name.trim())}}><button type="button" className="close" onClick={close}><X/></button><span className="eyebrow">{pending?'Gem dit svar':'Din liste venter'}</span><h2>Hvem skal<br/><em>med?</em></h2><p>Vælg et navn, så får du en offentlig koncertliste, der virker på tværs af enheder. Ingen mail. Intet bøvl.</p><label>DIT NAVN<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="fx Anna" maxLength="24"/></label>{error&&<div className="form-error">{error}</div>}<button className="submit" disabled={busy}>{busy?'Opretter…':'Lav min liste →'}</button><small>Din profil og dine koncertsvar gemmes sikkert i skyen.</small></form></div>}
function Home({user,onLogin,rsvps,onRsvp}){const[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[limit,setLimit]=useState(14);const upcoming=useMemo(()=>upcomingConcerts(),[]),chips=useMemo(()=>activeVenues(upcoming),[upcoming]);const matches=useMemo(()=>{const q=query.trim().toLowerCase();return upcoming.filter(c=>(filter==='all'||c.venueId===filter)&&(!q||c.artist.toLowerCase().includes(q)||c.genre.toLowerCase().includes(q)||venueById(c.venueId).name.toLowerCase().includes(q)))},[upcoming,filter,query]),items=matches.slice(0,limit);useEffect(()=>setLimit(14),[filter,query]);return <><section className="hero"><div className="hero-copy"><i className="dots"/><span className="eyebrow">DIN NÆSTE STORE AFTEN →</span><h1>Se hvad dine venner <em>skal se.</em></h1><p>Koncerter i København samlet ét sted. Sig <strong>»jeg kommer!«</strong> — eller et blødt måske — og del din liste med ét link.</p><div className="hero-actions"><button onClick={()=>document.querySelector('#feed').scrollIntoView({behavior:'smooth'})}>Find koncerter ↓</button><button onClick={onLogin}>{user?'Se min liste':'Start din liste'} <Share2/></button></div></div><ShareCard user={user} onLogin={onLogin} rsvps={rsvps}/></section><main id="feed"><div className="feed-head"><div><span className="eyebrow">OPDAG</span><h2>Hvad spiller?</h2></div><label className="search"><Search/><input aria-label="Søg efter artist, genre eller spillested" placeholder="Søg artist…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="chips"><button className={filter==='all'?'on':''} onClick={()=>setFilter('all')}>Alle</button>{chips.map(v=><button key={v.id} className={filter===v.id?'on':''} onClick={()=>setFilter(v.id)}>{v.name}</button>)}</div><div className="result-count">{matches.length} kommende {matches.length===1?'koncert':'koncerter'}</div><ConcertList items={items} rsvps={rsvps} onRsvp={onRsvp} empty="Ingen koncerter matcher din søgning."/>{items.length<matches.length&&<button className="more" onClick={()=>setLimit(x=>x+14)}>Vis flere <ChevronDown/></button>}</main></>}
function Venues({setVenue}){const upcoming=useMemo(()=>upcomingConcerts(),[]);return <main className="subpage"><span className="eyebrow">KBH & OMEGN</span><h1>Spillestederne.</h1><p className="intro">Fra intime kældre til sale med plads til hele vennegruppen.</p><div className="venue-grid">{venues.map((v,i)=>{const n=upcoming.filter(c=>c.venueId===v.id).length;return <button key={v.id} onClick={()=>setVenue(v)}><span>{String(i+1).padStart(2,'0')}</span><h2>{v.name}</h2><p><MapPin/> {v.area}</p><b>{n?`${n} kommende →`:'Se kalender →'}</b></button>})}</div></main>}
function VenuePage({venue,back,rsvps,onRsvp}){const items=useMemo(()=>upcomingConcerts().filter(c=>c.venueId===venue.id),[venue.id]);return <main className="subpage"><button className="back" onClick={back}>← Alle spillesteder</button><section className="venue-hero"><i className="dots"/><span className="eyebrow">SPILLESTED</span><h1>{venue.name}</h1><p><MapPin/> {venue.address} · {venue.area}</p><a href={venue.url} target="_blank" rel="noopener noreferrer">Officiel kalender <ExternalLink/></a></section><div className="section-title"><h2>Kommende koncerter</h2><span>{items.length}</span></div><ConcertList items={items} rsvps={rsvps} onRsvp={onRsvp}/></main>}
function Profile({user,rsvps,onRsvp,isOwner=true}){const[copied,setCopied]=useState(false);let go=concerts.filter(c=>rsvps[c.id]==='going'),maybe=concerts.filter(c=>rsvps[c.id]==='maybe');return <main className="subpage profile"><div className="profile-hero"><div className="big-avatar">{user.name[0]}</div><div><span className="eyebrow">OFFENTLIG LISTE</span><h1>{user.name}s koncerter.</h1><p>plusen.dk/{user.username}</p></div>{isOwner&&<button onClick={()=>copyLink(user.username,()=>{setCopied(true);setTimeout(()=>setCopied(false),2000)})}>{copied?'Kopieret!':'Kopiér link'} <Copy/></button>}</div><div className="section-title pink"><h2>Jeg kommer!</h2><span>{go.length}</span></div><ConcertList items={go} rsvps={rsvps} onRsvp={onRsvp} readOnly={!isOwner} empty="Du har ikke sagt ja endnu. Det kan nås!"/><div className="section-title yellow"><h2>Jeg overvejer…</h2><span>{maybe.length}</span></div><ConcertList items={maybe} rsvps={rsvps} onRsvp={onRsvp} readOnly={!isOwner} empty="Ingen løse planer — endnu."/></main>}
function App(){
  const[user,setUser]=useState(null),[rsvps,setRsvps]=useState({}),[page,setPage]=useState('home'),[venue,setVenue]=useState(null),[modal,setModal]=useState(false),[pending,setPending]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[publicList,setPublicList]=useState(null);
  // Delelinket er /<brugernavn> (Netlify sender alle ruter til index.html). ?u= holdes i live for gamle links.
  useEffect(()=>{(async()=>{try{const shared=decodeURIComponent(location.pathname.replace(/^\/+|\/+$/g,''))||new URLSearchParams(location.search).get('u');if(shared){setPage('shared');setPublicList(await loadPublicProfile(shared))}const current=await loadCurrentUser();setUser(current);if(current)setRsvps(await loadRsvps(current.id))}catch(e){setError(e.message)}finally{setBusy(false)}})()},[]);
  const request=async(id,type)=>{if(!user){setPending({id,type});setModal(true);return}const before=rsvps[id]??null;setRsvps(x=>({...x,[id]:type}));setError('');try{await saveRsvp(user.id,id,type)}catch(e){setRsvps(x=>({...x,[id]:before}));setError(`Kunne ikke gemme dit svar: ${e.message}`)}};
  const login=async name=>{setBusy(true);setError('');try{const next=await createCloudProfile(name);setUser(next);const nextRsvps=await loadRsvps(next.id);if(pending){await saveRsvp(next.id,pending.id,pending.type);nextRsvps[pending.id]=pending.type}setRsvps(nextRsvps);setPending(null);setModal(false)}catch(e){setError(e.message)}finally{setBusy(false)}};
  useEffect(()=>{const f=()=>{if(location.hash.startsWith('#venue:')){let v=venueById(location.hash.slice(7));if(v){setVenue(v);setPage('venue')}}};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);
  if(busy&&!user&&!modal)return <div className="boot"><span className="logo">+1</span><p>Henter koncertplaner…</p></div>;
  return <div className="site"><Header page={page} setPage={p=>{setPage(p);setVenue(null);scrollTo(0,0)}} user={user} onLogin={()=>setModal(true)}/>{!cloudConfigured&&<div className="config-warning">Cloud-databasen mangler opsætning. Tilføj Supabase-variablerne fra <code>.env.example</code>.</div>}{error&&!modal&&<div className="page-error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Luk besked"><X size={14}/></button></div>}{page==='home'&&<Home user={user} onLogin={()=>user?setPage('profile'):setModal(true)} rsvps={rsvps} onRsvp={request}/>} {page==='venues'&&<Venues setVenue={v=>{setVenue(v);setPage('venue');scrollTo(0,0)}}/>}{page==='venue'&&venue&&<VenuePage venue={venue} back={()=>setPage('venues')} rsvps={rsvps} onRsvp={request}/>} {page==='profile'&&user&&<Profile user={user} rsvps={rsvps} onRsvp={request}/>} {page==='shared'&&(publicList?<Profile user={publicList.user} rsvps={publicList.rsvps} onRsvp={request} isOwner={publicList.user.id===user?.id}/>:<main className="subpage empty">Listen findes ikke.</main>)}<footer><b>+1</b><span>koncerter i KBH & omegn</span><span>gratis at sige ja ✶</span></footer>{modal&&<LoginModal close={()=>{setModal(false);setPending(null);setError('')}} login={login} pending={pending} error={error} busy={busy}/>}</div>
}
createRoot(document.getElementById('root')).render(<App/>);
